### ISSUE TITLE
Post order and purchase form urls

### ISSUE THREAD

**Issue by rxng** [greatjack1/Amazon-Purchase-Bot#1]
I am trying to set this up on Amazon.com.au , but I cannot find the reference to this url anywhere In the site buttons 
https://www.amazon.com/gp/product/handle-buy-box/ref=dp_start-bbf_1_glance

is this url the same for every version of Amazon site? That means all we need to change is .com to .com.au ?

thank you for creating this!

**Comment by greatjack1** [comment]
Hey there,

That's a great question, To be 100% sure I would recommend using a tool like HTTP Toolkit, turning off js in your browser using no script and then completing the amazon buy process.

You should then be able to see which urls it accessed and replace the buy stage urls in the code with the ones you see in HTTP Toolkit.

Assuming amazon.com.au does use the same code then yes, it should just be a matter of changing all the urls to amazon.com.au.

Let me know how it goes and feel free to submit a pr adding localization support!

**Comment by rxng** [comment]
@greatjack1 did what you suggested and can confirm that the urls are correct - just add the country tld to the url!

However, the actually purchasing runs into an error ( I am using a [test product](https://www.amazon.com.au/gp/product/B08FB8222G))

```
Detected out of stock item as now in stock, pruchasing.....
No form html available, aborting....
We encountered an error when checking items!! Will retry in 30 seconds
Finished checking items, will restart in 30 seconds...
```

When I inspect the page html, the form id is indeed addToCart , the issue is in the spc-form it seems. 

*update*: after many tries on the cookies I finally got it to work.  Suggest to use http tool also rather than browser itself
